version: '3'

services:

  node-exporter:
    image: jahrik/arm-node-exporter:arm32v7
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    # ports:
    #   - 9100:9100
    deploy:
      mode: global
